name: DeployToHeroku

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HerokuLogin
        run : cat >~/.netrc <<EOF 
            machine api.heroku.com login mailbox.viksharma@gmail.com password ${{secrets.HEROKU_API_KEY}}
            EOF
        
